# This is a basic workflow to help you get started with Actions

name: CD babel-load

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: package install with npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          npm install --production
          npm list --depth=0

      - name: webpack build
        run: npx webpack
        
      - name: autoprefixer
        run: npm run ie11

      - name: Configure AWS credentials from IAM
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: upload AWS S3
        run: |
          aws s3 sync s3://aws-s3-tokyo s3://aws-s3-tokyo/backup \
            --exclude "backup/*" \
            --exclude "license/*"
          aws s3 sync ./dist s3://aws-s3-tokyo
